import { PageDefinition, ComponentInstance, DataSourceConfig } from '../types/builder';
import JSZip from 'jszip';

/**
 * SPA Export Service - Exports site pages as Spring Boot + React SPA project
 *
 * Instead of Thymeleaf SSR templates, this generates:
 * - A Spring Boot backend with site-runtime library (SPA controller, Page API, Security)
 * - A React SPA frontend that renders components from page JSON definitions
 * - Plugin bundles loaded dynamically at runtime
 */

// Map to track original URLs to their new static paths
let imageUrlMap: Map<string, string> = new Map();

interface ApiEndpointConfig {
  endpoint: string;
  dataPath: string;
  controllerName: string;
  methodName: string;
  routePath: string;
}

interface SpaExportOptions {
  projectName: string;
  groupId: string;
  artifactId: string;
  version: string;
  springBootVersion: string;
  javaVersion: string;
  authType?: 'none' | 'social' | 'sso';
  siteRuntimeVersion?: string;
}

interface PageExportData {
  pageName: string;
  path: string;
  definition: PageDefinition;
}

function camelToKebab(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function toJavaPackageName(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, '');
}

function getJavaPackage(options: SpaExportOptions): string {
  return `${options.groupId}.${toJavaPackageName(options.artifactId)}`;
}

function generateInlineStyle(styles: Record<string, any>): string {
  if (!styles || Object.keys(styles).length === 0) return '';
  const cssProperties: string[] = [];
  for (const [key, value] of Object.entries(styles)) {
    if (value !== undefined && value !== null && value !== '') {
      const cssKey = camelToKebab(key);
      cssProperties.push(`${cssKey}: ${value}`);
    }
  }
  return cssProperties.join('; ');
}

function escapeHtml(text: string): string {
  if (typeof text !== 'string') return String(text || '');
  const htmlEntities: Record<string, string> = {
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  };
  return text.replace(/[&<>"']/g, char => htmlEntities[char]);
}

/**
 * Safe filename from URL
 */
function urlToFilename(url: string): string {
  try {
    const urlObj = new URL(url);
    const pathParts = urlObj.pathname.split('/').filter(Boolean);
    const filename = pathParts.pop() || 'image';
    return filename.replace(/[^a-zA-Z0-9._-]/g, '_');
  } catch {
    return url.replace(/[^a-zA-Z0-9._-]/g, '_').substring(0, 50);
  }
}

// ============================================================
// REACT SPA GENERATOR
// ============================================================

/**
 * Generate the React SPA app.js bundle source code.
 * This is a standalone React app that:
 * - Fetches page definitions from /api/pages/{name}
 * - Renders components from the page JSON
 * - Handles client-side routing
 * - Loads plugin bundles dynamically
 */
function generateSpaAppJs(pages: PageExportData[]): string {
  const routes = pages.map(p => {
    const path = p.path === '/' ? '/' : p.path;
    return `  { path: '${path}', pageName: '${p.pageName}' }`;
  }).join(',\n');

  return `/**
 * VSD Site Runtime - React SPA Renderer
 * Auto-generated by Visual Site Designer
 */
(function() {
  'use strict';

  const React = window.React;
  const ReactDOM = window.ReactDOM;
  const { useState, useEffect, useCallback, createContext, useContext } = React;

  // ---- Context for plugin integration ----
  const PluginContextRegistryContext = createContext(new Map());

  // Expose VSD API for plugins
  window.__VSD__ = {
    PluginContextRegistryContext,
    registerPluginContextValue: function(contextId, value) {
      // Will be wired up by the App component
      if (window.__VSD__._registerFn) {
        window.__VSD__._registerFn(contextId, value);
      }
    },
    unregisterPluginContextValue: function(contextId) {
      if (window.__VSD__._unregisterFn) {
        window.__VSD__._unregisterFn(contextId);
      }
    }
  };

  // ---- Route definitions ----
  const ROUTES = [
${routes}
  ];

  // ---- Component Renderer ----
  function ComponentRenderer({ component, dataSources }) {
    const { componentId, props, styles, children, instanceId, templateBindings } = component;
    const style = styles || {};
    const key = 'component-' + instanceId;

    // Resolve template bindings
    const resolvedProps = { ...props };
    if (templateBindings && dataSources) {
      for (const [propName, template] of Object.entries(templateBindings)) {
        if (typeof template === 'string' && template.includes('{{')) {
          resolvedProps[propName] = resolveTemplate(template, dataSources);
        }
      }
    }

    // Check for plugin-rendered component
    const pluginRenderer = window.__VSD_RENDERERS__ && window.__VSD_RENDERERS__[componentId];
    if (pluginRenderer) {
      return React.createElement(pluginRenderer, {
        key, ...resolvedProps, style,
        children: renderChildren(children, dataSources)
      });
    }

    // Built-in component rendering
    switch (componentId) {
      case 'Label':
        return renderLabel(key, resolvedProps, style);
      case 'Button':
        return renderButton(key, resolvedProps, style, component.events);
      case 'Image':
        return renderImage(key, resolvedProps, style);
      case 'Container':
      case 'ScrollableContainer':
        return renderContainer(key, resolvedProps, style, children, dataSources);
      case 'Navbar':
      case 'NavbarDefault':
      case 'NavbarCentered':
      case 'NavbarMinimal':
      case 'NavbarDark':
      case 'NavbarGlass':
      case 'NavbarSticky':
        return renderNavbar(key, resolvedProps, style);
      default:
        return renderGeneric(key, componentId, resolvedProps, style, children, dataSources);
    }
  }

  function renderChildren(children, dataSources) {
    if (!children || children.length === 0) return null;
    return children.map(function(child) {
      return React.createElement(ComponentRenderer, {
        key: child.instanceId, component: child, dataSources: dataSources
      });
    });
  }

  function resolveTemplate(template, dataSources) {
    return template.replace(/\\{\\{([^}]+)\\}\\}/g, function(_, path) {
      return getNestedValue(dataSources, path) || '';
    });
  }

  function getNestedValue(obj, path) {
    return path.split('.').reduce(function(o, k) { return o && o[k]; }, obj);
  }

  // ---- Built-in Renderers ----

  function renderLabel(key, props, style) {
    const tagMap = { h1:'h1', h2:'h2', h3:'h3', h4:'h4', h5:'h5', h6:'h6', paragraph:'p', span:'span', label:'label' };
    const tag = tagMap[props.variant] || 'span';
    return React.createElement(tag, { key, style, className: 'component label' }, props.text || '');
  }

  function renderButton(key, props, style, events) {
    const clickEvent = events && events.find(function(e) { return e.eventType === 'onClick'; });
    const onClick = function() {
      if (clickEvent && clickEvent.action && clickEvent.action.type === 'navigate' && clickEvent.action.config && clickEvent.action.config.url) {
        navigateTo(clickEvent.action.config.url);
      }
    };

    if (clickEvent && clickEvent.action && clickEvent.action.type === 'navigate') {
      return React.createElement('a', {
        key, style, className: 'component button',
        href: clickEvent.action.config.url,
        onClick: function(e) { e.preventDefault(); onClick(); }
      }, props.text || 'Click Me');
    }
    return React.createElement('button', { key, style, className: 'component button', onClick: onClick },
      props.text || 'Click Me');
  }

  function renderImage(key, props, style) {
    const src = props.src || props.url || '';
    const alt = props.alt || '';
    const objectFit = props.objectFit || 'cover';
    const objectPosition = props.objectPosition || 'center';

    const containerStyle = { ...style, position: 'relative', overflow: 'hidden' };
    const imgStyle = { width: '100%', height: '100%', objectFit: objectFit, objectPosition: objectPosition };

    return React.createElement('div', { key, style: containerStyle, className: 'component image-container' },
      React.createElement('img', { src: src, alt: alt, style: imgStyle, loading: 'lazy' })
    );
  }

  function renderContainer(key, props, style, children, dataSources) {
    const layoutMode = props.layoutMode || 'flex-column';
    const layoutStyles = getLayoutStyles(layoutMode, props);
    const mergedStyle = { ...layoutStyles, ...style };

    return React.createElement('div', { key, style: mergedStyle, className: 'component container' },
      renderChildren(children, dataSources)
    );
  }

  function renderNavbar(key, props, style) {
    const brandName = props.brandName || props.brand || 'Site';
    const items = props.items || props.navItems || [];
    const navStyle = {
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      padding: '12px 24px', ...style
    };

    return React.createElement('nav', { key, style: navStyle, className: 'component navbar' },
      React.createElement('a', {
        href: '/', className: 'navbar-brand',
        style: { fontWeight: 'bold', fontSize: '1.25rem', textDecoration: 'none', color: 'inherit' },
        onClick: function(e) { e.preventDefault(); navigateTo('/'); }
      }, brandName),
      React.createElement('div', { style: { display: 'flex', gap: '16px' } },
        items.map(function(item, i) {
          return React.createElement('a', {
            key: i, href: item.url || item.href || '#',
            style: { textDecoration: 'none', color: 'inherit' },
            onClick: function(e) {
              if (item.url || item.href) { e.preventDefault(); navigateTo(item.url || item.href); }
            }
          }, item.label || item.text || '');
        })
      )
    );
  }

  function renderGeneric(key, componentId, props, style, children, dataSources) {
    return React.createElement('div', {
      key, style: style, className: 'component ' + componentId.toLowerCase()
    }, renderChildren(children, dataSources));
  }

  function getLayoutStyles(layoutMode, props) {
    var base = { display: 'flex', boxSizing: 'border-box' };
    switch (layoutMode) {
      case 'flex-row': return { ...base, flexDirection: 'row', gap: props.gap || '8px' };
      case 'flex-column': return { ...base, flexDirection: 'column', gap: props.gap || '8px' };
      case 'flex-wrap': return { ...base, flexDirection: 'row', flexWrap: 'wrap', gap: props.gap || '8px' };
      case 'grid-2col': return { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: props.gap || '8px' };
      case 'grid-3col': return { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: props.gap || '8px' };
      case 'grid-4col': return { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: props.gap || '8px' };
      default: return { ...base, flexDirection: 'column', gap: props.gap || '8px' };
    }
  }

  // ---- Client-side Router ----
  function navigateTo(path) {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  }

  function useRouter() {
    const [currentPath, setCurrentPath] = useState(window.location.pathname);

    useEffect(function() {
      function handlePopState() { setCurrentPath(window.location.pathname); }
      window.addEventListener('popstate', handlePopState);
      return function() { window.removeEventListener('popstate', handlePopState); };
    }, []);

    return currentPath;
  }

  // ---- Page Component ----
  function Page({ pageName }) {
    const [pageData, setPageData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(function() {
      setLoading(true);
      setError(null);
      fetch('/api/pages/' + pageName, { credentials: 'same-origin' })
        .then(function(res) {
          if (!res.ok) throw new Error('Page not found');
          return res.json();
        })
        .then(function(data) {
          setPageData(data);
          setLoading(false);
        })
        .catch(function(err) {
          setError(err.message);
          setLoading(false);
        });
    }, [pageName]);

    if (loading) {
      return React.createElement('div', { className: 'page-loading', style: {
        display: 'flex', justifyContent: 'center', alignItems: 'center',
        minHeight: '200px', color: '#666'
      }}, 'Loading...');
    }

    if (error) {
      return React.createElement('div', { className: 'page-error', style: {
        display: 'flex', justifyContent: 'center', alignItems: 'center',
        minHeight: '200px', color: '#e53e3e'
      }}, 'Error: ' + error);
    }

    if (!pageData) return null;

    const components = pageData.components || [];
    const dataSources = pageData.data || {};

    return React.createElement('div', { className: 'page', 'data-page': pageName },
      components.map(function(component) {
        return React.createElement(ComponentRenderer, {
          key: component.instanceId, component: component, dataSources: dataSources
        });
      })
    );
  }

  // ---- App Component ----
  function App() {
    const currentPath = useRouter();
    const [contextRegistry, setContextRegistry] = useState(new Map());

    // Wire up plugin context registration
    useEffect(function() {
      window.__VSD__._registerFn = function(contextId, value) {
        setContextRegistry(function(prev) {
          const next = new Map(prev);
          next.set(contextId, value);
          return next;
        });
      };
      window.__VSD__._unregisterFn = function(contextId) {
        setContextRegistry(function(prev) {
          const next = new Map(prev);
          next.delete(contextId);
          return next;
        });
      };
    }, []);

    // Find matching route
    var matchedRoute = null;
    for (var i = 0; i < ROUTES.length; i++) {
      if (ROUTES[i].path === currentPath || ROUTES[i].path === currentPath.replace(/\\/$/, '')) {
        matchedRoute = ROUTES[i];
        break;
      }
    }
    // Default to first route (home) if no match
    if (!matchedRoute && ROUTES.length > 0) {
      // Check for home page
      matchedRoute = ROUTES.find(function(r) { return r.path === '/'; }) || ROUTES[0];
    }

    return React.createElement(
      PluginContextRegistryContext.Provider,
      { value: contextRegistry },
      matchedRoute
        ? React.createElement(Page, { key: matchedRoute.pageName, pageName: matchedRoute.pageName })
        : React.createElement('div', { className: 'page-not-found' }, '404 - Page Not Found')
    );
  }

  // ---- Bootstrap ----
  var root = document.getElementById('root');
  if (root) {
    if (ReactDOM.createRoot) {
      ReactDOM.createRoot(root).render(React.createElement(App));
    } else {
      ReactDOM.render(React.createElement(App), root);
    }
  }
})();
`;
}

/**
 * Generate the SPA index.html entry point
 */
function generateIndexHtml(projectName: string, pluginBundles: string[]): string {
  const pluginScripts = pluginBundles
    .map(name => `    <script src="/js/plugins/${name}"></script>`)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(projectName)}</title>
    <link rel="stylesheet" href="/css/styles.css" />
</head>
<body>
    <div id="root"></div>

    <!-- React (production) -->
    <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>

    <!-- VSD SPA Runtime -->
    <script src="/js/app.js"></script>

    <!-- Plugin Bundles (dynamically loaded at runtime) -->
${pluginScripts}
</body>
</html>
`;
}

// ============================================================
// SPRING BOOT PROJECT GENERATORS
// ============================================================

function generatePomXml(options: SpaExportOptions, hasApiEndpoints: boolean): string {
  const pkg = getJavaPackage(options);
  const siteRuntimeVersion = options.siteRuntimeVersion || '1.0.0-SNAPSHOT';

  let lombokDep = '';
  if (hasApiEndpoints) {
    lombokDep = `
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>`;
  }

  let authDeps = '';
  if (options.authType && options.authType !== 'none') {
    authDeps = `

        <!-- Security & OAuth2 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>`;
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>${options.springBootVersion}</version>
        <relativePath />
    </parent>

    <groupId>${options.groupId}</groupId>
    <artifactId>${options.artifactId}</artifactId>
    <version>${options.version}</version>
    <name>${options.projectName}</name>
    <description>Generated by Visual Site Designer</description>

    <properties>
        <java.version>${options.javaVersion}</java.version>
    </properties>

    <dependencies>
        <!-- Spring Boot Starter Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- VSD Site Runtime (SPA controller, Page API, Security, Data fetching) -->
        <dependency>
            <groupId>dev.mainul35</groupId>
            <artifactId>site-runtime</artifactId>
            <version>${siteRuntimeVersion}</version>
        </dependency>

        <!-- JSON processing -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>${authDeps}${lombokDep}
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
`;
}

function generateApplicationJava(options: SpaExportOptions): string {
  const pkg = getJavaPackage(options);
  return `package ${pkg};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
`;
}

function generateApplicationProperties(options: SpaExportOptions): string {
  let props = `# Server configuration
server.port=8080

# VSD Site Runtime configuration
site.runtime.api.gateway-url=http://localhost:8080
site.runtime.api.timeout-ms=30000
site.runtime.cache.type=memory
site.runtime.cache.default-ttl-ms=60000
`;

  if (options.authType === 'social') {
    props += `
# Authentication - Social Login
site.runtime.auth.type=social
site.runtime.auth.login-success-url=/
site.runtime.auth.logout-success-url=/

# Google OAuth2 (uncomment and configure)
# site.runtime.auth.social.google.enabled=true
# site.runtime.auth.social.google.client-id=your-google-client-id
# site.runtime.auth.social.google.client-secret=your-google-client-secret

# GitHub OAuth2 (uncomment and configure)
# site.runtime.auth.social.github.enabled=true
# site.runtime.auth.social.github.client-id=your-github-client-id
# site.runtime.auth.social.github.client-secret=your-github-client-secret
`;
  } else if (options.authType === 'sso') {
    props += `
# Authentication - SSO
site.runtime.auth.type=sso
site.runtime.auth.login-success-url=/
site.runtime.auth.logout-success-url=/

# SSO Provider (okta, keycloak, azure, custom)
# site.runtime.auth.sso.provider=keycloak
# site.runtime.auth.sso.client-id=your-client-id
# site.runtime.auth.sso.client-secret=your-client-secret
# site.runtime.auth.sso.auth-server-url=http://localhost:8180
# site.runtime.auth.sso.realm=your-realm
`;
  } else {
    props += `
# Authentication - disabled (permit all)
site.runtime.auth.type=none
`;
  }

  props += `
# Database (optional - uncomment to enable)
# site.runtime.database.type=jpa
# spring.datasource.url=jdbc:mysql://localhost:3306/mysite
# spring.datasource.username=root
# spring.datasource.password=password

# Logging
logging.level.dev.mainul35=INFO
`;

  return props;
}

function generateBaseCSS(): string {
  return `/* VSD Site Runtime - Base Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  line-height: 1.6;
  color: #333;
}

#root {
  min-height: 100vh;
}

.page {
  min-height: 100vh;
}

.page-loading, .page-error, .page-not-found {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 50vh;
  font-size: 1.1rem;
}

.page-error { color: #e53e3e; }
.page-not-found { color: #666; }

/* Component base styles */
.component { box-sizing: border-box; }
.component.button {
  cursor: pointer;
  border: none;
  display: inline-block;
  text-decoration: none;
}
.component.label { display: block; }
.component.container { box-sizing: border-box; }
.component.navbar { width: 100%; }
.component.image-container img {
  display: block;
  max-width: 100%;
}

/* Responsive utilities */
@media (max-width: 768px) {
  .component.navbar {
    flex-direction: column;
    gap: 8px;
  }
}
`;
}

function generateDockerfile(options: SpaExportOptions): string {
  return `FROM eclipse-temurin:${options.javaVersion}-jre
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
`;
}

function generateReadme(options: SpaExportOptions, pages: PageExportData[]): string {
  const pageList = pages.map(p => `- **${p.pageName}** (\`${p.path}\`)`).join('\n');

  return `# ${options.projectName}

Generated by [Visual Site Designer](https://github.com/mainul35) - React SPA with Spring Boot backend.

## Pages
${pageList}

## Architecture

This is a **Single Page Application (SPA)** with:
- **Frontend**: React SPA loaded from \`/static/js/app.js\`
- **Backend**: Spring Boot with VSD Site Runtime library
- **Plugins**: IIFE bundles loaded from \`/static/js/plugins/\`
- **Page Data**: Served as JSON from \`/api/pages/{name}\`
- **Security**: Configured via \`application.properties\` (none/social/sso)

## Prerequisites
- Java ${options.javaVersion}
- Maven 3.8+

## Running Locally
\`\`\`bash
mvn spring-boot:run
\`\`\`
Then open http://localhost:8080

## Building for Production
\`\`\`bash
mvn clean package
java -jar target/${options.artifactId}-${options.version}.jar
\`\`\`

## Docker
\`\`\`bash
docker build -t ${options.artifactId} .
docker run -p 8080:8080 ${options.artifactId}
\`\`\`

## Adding Plugins

Drop plugin IIFE bundles into \`src/main/resources/static/js/plugins/\` and
add a \`<script>\` tag in \`src/main/resources/static/index.html\`.

## Authentication

Configure authentication in \`application.properties\`:
- \`site.runtime.auth.type=none\` — No authentication (default)
- \`site.runtime.auth.type=social\` — Google/GitHub/Facebook OAuth2
- \`site.runtime.auth.type=sso\` — Okta/Keycloak/Azure AD/Custom OIDC

## Project Structure
\`\`\`
${options.artifactId}/
├── pom.xml
├── Dockerfile
├── src/main/
│   ├── java/${options.groupId.replace(/\./g, '/')}/${toJavaPackageName(options.artifactId)}/
│   │   └── Application.java
│   └── resources/
│       ├── application.properties
│       ├── pages/              ← Page data (JSON)
│       └── static/
│           ├── index.html      ← SPA entry point
│           ├── css/styles.css
│           ├── js/
│           │   ├── app.js      ← React SPA renderer
│           │   └── plugins/    ← Plugin bundles
│           └── images/
\`\`\`
`;
}

// ============================================================
// IMAGE COLLECTION
// ============================================================

function collectStaticImageUrls(components: ComponentInstance[]): Set<string> {
  const urls = new Set<string>();

  for (const component of components) {
    const src = component.props?.src || component.props?.url;
    if (src && typeof src === 'string' && !src.includes('{{')) {
      if (src.startsWith('http://') || src.startsWith('https://') || src.startsWith('/')) {
        urls.add(src);
      }
    }
    const bgImage = component.styles?.backgroundImage;
    if (bgImage && typeof bgImage === 'string') {
      const match = bgImage.match(/url\(['"]?([^'")\s]+)['"]?\)/);
      if (match && match[1] && !match[1].includes('{{')) {
        urls.add(match[1]);
      }
    }
    if (component.children) {
      for (const url of collectStaticImageUrls(component.children)) {
        urls.add(url);
      }
    }
  }

  return urls;
}

async function collectAndAddImages(
  zip: JSZip,
  pages: PageExportData[],
  basePath: string
): Promise<Map<string, string>> {
  const urlMap = new Map<string, string>();
  const allUrls = new Set<string>();

  for (const page of pages) {
    for (const url of collectStaticImageUrls(page.definition.components)) {
      allUrls.add(url);
    }
  }

  for (const url of allUrls) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        const blob = await response.blob();
        const filename = urlToFilename(url);
        const newPath = `/images/${filename}`;
        zip.file(`${basePath}/src/main/resources/static/images/${filename}`, blob);
        urlMap.set(url, newPath);
      }
    } catch {
      // Skip images that can't be fetched
    }
  }

  return urlMap;
}

// ============================================================
// API ENDPOINT COLLECTION
// ============================================================

function collectApiEndpoints(pages: PageExportData[]): ApiEndpointConfig[] {
  const endpoints = new Map<string, ApiEndpointConfig>();

  for (const page of pages) {
    collectComponentEndpoints(page.definition.components, endpoints);
  }

  return Array.from(endpoints.values());
}

function collectComponentEndpoints(
  components: ComponentInstance[],
  endpoints: Map<string, ApiEndpointConfig>
): void {
  for (const component of components) {
    if (component.dataSource?.type === 'api' && component.dataSource.endpoint) {
      const endpoint = component.dataSource.endpoint;
      if (!endpoints.has(endpoint)) {
        const parts = endpoint.split('/').filter(Boolean);
        const methodName = 'get' + parts.map(p =>
          p.charAt(0).toUpperCase() + p.slice(1)
        ).join('');
        endpoints.set(endpoint, {
          endpoint,
          dataPath: component.iteratorConfig?.dataPath || 'items',
          controllerName: 'ApiDataController',
          methodName,
          routePath: endpoint,
        });
      }
    }
    if (component.children) {
      collectComponentEndpoints(component.children, endpoints);
    }
  }
}

function collectComponentDataSources(components: ComponentInstance[]): Record<string, any> {
  const dataSources: Record<string, any> = {};

  for (const component of components) {
    if (component.dataSource?.type === 'static' && component.dataSource.staticData) {
      dataSources[`repeater_${component.instanceId}`] = component.dataSource.staticData;
    }
    if (component.children) {
      Object.assign(dataSources, collectComponentDataSources(component.children));
    }
  }

  return dataSources;
}

// ============================================================
// MAIN EXPORT FUNCTION
// ============================================================

export async function exportAsSpaProject(
  pages: PageExportData[],
  options: Partial<SpaExportOptions> = {}
): Promise<Blob> {
  const defaults: SpaExportOptions = {
    projectName: 'my-site',
    groupId: 'com.example',
    artifactId: 'my-site',
    version: '1.0.0',
    springBootVersion: '3.2.0',
    javaVersion: '21',
    authType: 'none',
    siteRuntimeVersion: '1.0.0-SNAPSHOT',
  };
  const opts: SpaExportOptions = { ...defaults, ...options };
  const basePath = opts.artifactId;
  const pkg = getJavaPackage(opts);
  const pkgPath = pkg.replace(/\./g, '/');

  const zip = new JSZip();

  // 1. Collect and add images
  imageUrlMap = await collectAndAddImages(zip, pages, basePath);

  // 2. Collect API endpoints
  const apiEndpoints = collectApiEndpoints(pages);

  // 3. Generate pom.xml
  zip.file(`${basePath}/pom.xml`, generatePomXml(opts, apiEndpoints.length > 0));

  // 4. Application.java
  zip.file(
    `${basePath}/src/main/java/${pkgPath}/Application.java`,
    generateApplicationJava(opts)
  );

  // 5. application.properties
  zip.file(
    `${basePath}/src/main/resources/application.properties`,
    generateApplicationProperties(opts)
  );

  // 6. Page definition JSON files
  for (const page of pages) {
    const pageDataSources = collectComponentDataSources(page.definition.components);
    const pageJson = {
      pageName: page.pageName,
      title: page.definition.pageName || page.pageName,
      description: '',
      path: page.path,
      components: page.definition.components,
      dataSources: pageDataSources,
    };
    zip.file(
      `${basePath}/src/main/resources/pages/${page.pageName}.json`,
      JSON.stringify(pageJson, null, 2)
    );
  }

  // 7. SPA frontend assets
  const pluginBundles: string[] = [];
  // TODO: In future, detect installed plugins and include their bundles
  // For now, generate with empty plugin list (users can add manually)

  zip.file(
    `${basePath}/src/main/resources/static/index.html`,
    generateIndexHtml(opts.projectName, pluginBundles)
  );
  zip.file(
    `${basePath}/src/main/resources/static/js/app.js`,
    generateSpaAppJs(pages)
  );
  zip.file(
    `${basePath}/src/main/resources/static/css/styles.css`,
    generateBaseCSS()
  );

  // 8. Placeholder for plugins directory
  zip.file(
    `${basePath}/src/main/resources/static/js/plugins/.gitkeep`,
    ''
  );

  // 9. Dockerfile & README
  zip.file(`${basePath}/Dockerfile`, generateDockerfile(opts));
  zip.file(`${basePath}/README.md`, generateReadme(opts, pages));

  return zip.generateAsync({ type: 'blob' });
}

export async function downloadSpaProject(
  pages: PageExportData[],
  options?: Partial<SpaExportOptions>
): Promise<void> {
  const blob = await exportAsSpaProject(pages, options);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${options?.artifactId || 'my-site'}-spa.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
